import type { Metadata } from "next";
import "./globals.scss";
import Nav from "./component/nav";

import { Noto_Sans_KR, Lemon } from "next/font/google";

const scanda = Lemon({
  // 사용할 font weight만 불러온다.
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-scanda",
  display: "swap",
});

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--roboto-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Sophie Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${notoSansKr.variable} ${scanda.variable}`}>
      <body>{children}</body>
    </html>
  );
}
